# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with a Python 3.13 base image
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Copy the project files into the container
COPY . .

# Install uv (ensure Python environment is prepared)
RUN pip install uv

# Install the project's dependencies using uv
RUN uv sync --frozen --no-dev --no-editable

# Expose the port that the server will run on (adjust if necessary)
EXPOSE 8000

# Define the default command to run the MCP server
CMD ["fastmcp", "dev", "server.py"]